server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///var/lib/wm-config-server/
          basedir: target/config

# Suppress warning that two discovery clients - Consul and Eureka - were found
eureka:
  client:
    enabled: false

