---
server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          basedir: target/config

# Suppress warning that two discovery clients - Consul and Eureka - were found
eureka:
  client:
    enabled: false

---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: file://${user.dir}/src/main/rpm/config-repo
          basedir: target/config
