server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          basedir: target/config

#security:
#  user:
#    password: '{cipher}AQBunH7b87s86E/k3YaISZe90th7eOMzxv/CupLgU4BD5ERo1FD4B2S9egNtqZE9jNI1BsycyDeFN+o207S8/iVhXw4lRX8bE15jLdF537uakNFIYvBSdRx7pjNwtcorCBogqmhAQWR3ZOovWOAGhLw8MgsXAgz8oPxvIdn9Fjjd+PAofV93X7CSXEN5hgPq+s4M+oPErTQgK4KfwJu2mBjdBHqlecUMKBcaeK5dVwbqFWsAH9hmIZ/jVhSZ56uveLtCVXqrrfEne9B/WPKF4KhpKskjfPszN2wwWwjLjo7xjzasMXp3qb9t8Si4mGqLPH3mmqKsCscw61we2RIg1t8W6oJpgKzt1DA00ms8zqgUjHZyyybGDujEKp37gzOhrRw='

# Suppress warning that two discovery clients - Consul and Eureka - were found
eureka:
  client:
    enabled: false

# TODO: move these profiles to the remote repo

---
spring:
  profiles: cloud
# no JCE in PWS
security:
  user:
    password: password
